# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:                                        # 1. CÀI CONTAINER MONGO TỪ DOCKER HUB
    # image: mongo:windowsservercore-ltsc2022   # Cách sử dụng phiên bản tùy chọn
    image: mongo                                # latest version
    container_name: mongo-container
    ports: 
      - 27018:27017
    volumes:
      - './mongodb:/data/db'                    # database đang chứa ở thư mục này (ánh xạ để bảo vệ dữ liệu khi crash xảy ra) => dữ liệu được restore lại ở thư mục './mongodb:' nên ko bị mất => kỹ thuật này gọi là ánh xạ volumes
    restart: always                             # Nếu container bị crash hoặc deception bị lỗi thì nó tự restart lại container này
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-express:                                # 2. CÀI CONTAINER MONGO-EXPRESS TỪ DOCKER HUB
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/


# Lệnh chạy
# --detach: Chạy ở chế độ chạy ngầm khi tắt cửa sổ terminal tắt đi thì vẫn còn chạy
# $ docker-compose -f mongo-compose.yml up --detach

# docker-compose -f mongo-compose.yml down                                                          # LỆNH NÀY DÙNG ĐỂ STOP CONTAINER VÀ XÓA LUÔN 2 CONTAINER NHƯNG IMAGES VẪN CÒN LƯU
# mongosh "mongodb://root:1234@localhost:27018" --username root --authenticationDatabase admin

# ===========================================
#           sample data is here:
# ===========================================
# https://atlas-education.s3.amazonaws.com/sampledata.archive


# ===========================================
#   access to mongo-container's terminal
# ===========================================
# cd C:\Users\sunli\Documents\code\YoutubeChannel\2023\MongoDBTutorialsForBeginners2023\myapp
# docker exec -it mongo-container bash


# ===========================================
#       Connect inside container:
# ===========================================
# mongosh "mongodb://root:1234@localhost:27017" --username root --authenticationDatabase admin
# use sample_mflix


# ===========================================
#       Download and restore data
# ===========================================
# curl https://atlas-education.s3.amazonaws.com/sampledata.archive -o sampledata.archive
# mongorestore --username root --password 1234 --authenticationDatabase admin --archive=./sampledata.archive